name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "30 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: imobasshir
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta

          plugin_lines: yes
          plugin_repositories: 100
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100

  language:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: imobasshir
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          config_display: large
          config_output: svg
          filename: language.svg

          # Language plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
  
  calender:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
        
          user: imobasshir
          filename: fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}  
          base: ""  
          plugin_isocalendar: yes  
          plugin_isocalendar_duration: full-year
          
